- name: tasks level variables
  hosts: local
  connection: local
  vars:
    COURSE: "DEVOPS with AWS"
    DURATION: "140HRS"
    TRAINER: "ISMAIL"
  tasks:
  - name: print variables
    vars:
     COURSE: Ansible
    ansible.builtin.debug:
     msg: "Course is: {{ COURSE }}, Trainer is: {{ TRAINER }}"